AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Pipes infrastructure as code

Parameters:
  Name:
    Type: String
    Description: The name of the api
    MinLength: 3
    MaxLength: 30
    Default: pipes-core-stack-local 
  Stage:
    Type: String
    Description: The stage of the api
    MinLength: 3
    MaxLength: 20
    Default: pre-dev

Globals:
  Function:
    Runtime: nodejs10.x
    Timeout: 20
    MemorySize: 128
    Environment:
      Variables:
        NODE_ENV:
          Fn::Sub: ${Stage}
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Name}-test-function-${Stage}
      Handler: index.handler
      CodeUri: ../functions/test/

  APIGatewayNestedStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: api-gateway.yaml
      Parameters:
        Name:
          Ref: Name
        Stage:
          Ref: Stage

Outputs:
  TestFunctionArn:
    Description: Printing out test function arn
    Value: 
      Fn::GetAtt [TestFunction, Arn]
