AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Pipes infrastructure as code

Parameters:
  Name:
    Type: String
    Description: The name of the api
    MinLength: 3
    MaxLength: 30
    Default: pipes
  Stage:
    Type: String
    Description: The stage of the api
    MinLength: 3
    MaxLength: 20
    Default: local 

Resources:
  APIGatewayNestedStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./apig-data-stream.yaml
      Parameters:
        Name:
          Ref: Name
        Stage:
          Ref: Stage

Outputs:
  TestFunctionArn:
    Description: Printing out test function arn
    Value: 
      Fn::GetAtt [TestFunction, Arn]
