AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Pipes infrastructure as code

Parameters:
  Name:
    Type: String
    Description: The name of the api
    MinLength: 3
    MaxLength: 30
    Default: pipes
  Stage:
    Type: String
    Description: The stage of the api
    MinLength: 3
    MaxLength: 20
    Default: local 

Resources:
  APIGatewayCollectorStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./collector-pipes-apig.yaml
      Parameters:
        Name:
          Ref: Name
        Stage:
          Ref: Stage
  GoogleAnalyticsCollectorStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./collector-ga.yaml
      Parameters:
        Name:
          Ref: Name
        Stage:
          Ref: Stage
