AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Monitoring Stack

Parameters:
  Name:
    Type: String
    Default: pipes-monitoring
  Stage:
    Type: String
    Default: dev
  AdminEmail:
    Type: String
    Default: dimitri+pipes@tarasowski.de
  S3AlarmPeriod:
    Type: String
    Default: 60 
  GoogleAnalyticsExportStackName:
    Type: String
    Default: google-analytics-export-stack-name

Resources:
  AlarmLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: "${Name}-lambda-put-metrics-role-${Stage}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com

  AlarmLambdaPolicy:
    DependsOn:
      - AlarmLambdaRole
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: 
        Fn::Sub: "${Name}-lambda-put-metrics-${Stage}"
      Roles:
        - Ref: AlarmLambdaRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricData
            Resource: '*'

  
  FunctionEmittingMetrics:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: "${Stage}-emitting-metrics-${Stage}"
      Handler: index.handler
      Runtime: python3.7
      Timeout: 5
      MemorySize: 128
      Role:
        Fn::GetAtt: [AlarmLambdaRole, Arn]
      Code:
        ZipFile: >
          import boto3;
          client = boto3.client('cloudwatch');

          def handler(event, context):
              return client.put_metric_data(
                  Namespace = 'Pipes',
                  MetricData = [
                      {
                          'MetricName': 'NewObjectAdded',
                          'Dimensions': [
                              {
                                  'Name': 'S3',
                                  'Value': 'successfully'
                              }],
                          'Value': 1,
                          'Unit': 'None'
                      }
                      ]
                  )
                  #      Events:
                  #        NewDataInBucket:
                  #          Type: S3
                  #          Properties:
                  #            Bucket:
                  #              Fn::ImportValue: 
                  #                Fn::Sub: "${GoogleAnalyticsExportStackName}-GADataBucket"
                  #            Events: 's3:ObjectCreated:*'
                  #            Filter:
                  #              S3Key:
                  #                Rules:
                  #                  - Name: prefix 
                  #                    Value: events/
                  #
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::Sub: "${Name}-alarm-${Stage}"
      TopicName: 
        Fn::Sub: "${Name}-alarm-${Stage}"

  AlarmTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: Id1
        Version: 2012-10-17
        Statement:
          - Sid: Sid1
            Effect: Allow
            Principal:
              AWS: '*'
            Action: 'sns:Publish'
            Resource:
              Ref: AlarmTopic
            Condition:
              StringEquals:
                'AWS:SourceOwner':
                  Ref: 'AWS::AccountId'
      Topics:
        - Ref: AlarmTopic

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint:
        Ref: AdminEmail
      Protocol: email
      TopicArn:
        Ref: AlarmTopic

  S3MissingDataAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: No New Pipes Data in S3 Bucket
      AlarmDescription: No new incoming data in your Pipes S3 bucket. Please check your Pipes configuration or send a support ticket to support@pipesdata.com 
      AlarmActions: 
        - Ref: AlarmTopic
      MetricName: NewObjectAdded
      Namespace: Pipes
      Statistic: Sum
      Period: 
        Ref: S3AlarmPeriod
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      TreatMissingData: breaching


