AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Monitoring Stack

Parameters:
  Name:
    Type: String
    Default: pipes-monitoring
  Stage:
    Type: String
    Default: dev
  AdminEmail:
    Type: String
    Default: dimitri+pipes@tarasowski.de
  S3AlarmPeriod:
    Type: String
    Default: 60 
  MonitoringEmitMetricsFunction:
    Type: String
    Default: monitoring-emit-metrics-function

Resources:
  AlarmLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: "${Name}-lambda-put-metrics-role-${Stage}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com

  AlarmLambdaPolicy:
    DependsOn:
      - AlarmLambdaRole
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: 
        Fn::Sub: "${Name}-lambda-put-metrics-${Stage}"
      Roles:
        - Ref: AlarmLambdaRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - cloudwatch:PutMetricData
            Resource: '*'
  
  EmitMetricsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName:
        Fn::Sub: "${Stage}-emitting-metrics-${Stage}"
      Handler: main.handler
      Runtime: python3.7
      Timeout: 5
      MemorySize: 128
      Role:
        Fn::GetAtt: [AlarmLambdaRole, Arn]
      CodeUri: ../functions/monitoring/s3

  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::Sub: "${Name}-alarm-${Stage}"
      TopicName: 
        Fn::Sub: "${Name}-alarm-${Stage}"

  AlarmTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: Id1
        Version: 2012-10-17
        Statement:
          - Sid: Sid1
            Effect: Allow
            Principal:
              AWS: '*'
            Action: 'sns:Publish'
            Resource:
              Ref: AlarmTopic
            Condition:
              StringEquals:
                'AWS:SourceOwner':
                  Ref: 'AWS::AccountId'
      Topics:
        - Ref: AlarmTopic

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint:
        Ref: AdminEmail
      Protocol: email
      TopicArn:
        Ref: AlarmTopic

  S3MissingDataAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: No New Google Analytics Data in S3 Bucket of Pipes
      AlarmDescription: No new incoming data in your Pipes S3 bucket. Please check your Pipes configuration or send a support ticket to support@pipesdata.com 
      AlarmActions: 
        - Ref: AlarmTopic
      MetricName: NewObjectAdded
      Dimensions:
        - Name: S3
          Value: successfully
      Namespace: Pipes
      Statistic: Sum
      Period: 
        Ref: S3AlarmPeriod
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      TreatMissingData: breaching

Outputs:
  MonitoringEmitMetricsFunctionName:
    Description: Referce to the monitoring function
    Value:
      Ref: EmitMetricsFunction
    Export: 
      Name:
        Fn::Sub: "${MonitoringEmitMetricsFunction}-${Name}-${Stage}-Name"
  MonitoringEmitMetricsFunctionArn:
    Description: Referce to the monitoring function
    Value:
      Fn::GetAtt: [EmitMetricsFunction, Arn]
    Export: 
      Name:
        Fn::Sub: "${MonitoringEmitMetricsFunction}-${Name}-${Stage}-Arn"
